### ISSUE TITLE
__typename must be const

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/grats#122]
Currently we allow this, but it's not technically safe since the `__typename` could be mutated.
```ts
class User implements IPerson {
  __typename = "User";
}
```

We should require either:

```ts
class User implements IPerson {
  __typename = "User" as const;
}
```

or 

```ts
class User implements IPerson {
  __typename: "User" = "User";
}
```

**Comment by Rash-Hit** [comment]
@captbaritone  can i take this ?? what all other things needs to in mind while doing this .

**Comment by captbaritone** [comment]
@Rash-Hit Sorry I missed your message! I think all we need to do here is update the code [here](https://github.com/captbaritone/grats/blob/2f7323fb43a31ed1895b394bbdbc01fba583cc0c/src/Extractor.ts#L719) to expect an "AsExpression" with an expression that is the expected string literal and a type that is `const` (I think there's a keyword constant exported by TypeScript somewhere).

Then you should be sure to update/add test fixtures showing the "happy" path as well as demonstrating exactly what the error messages look like. You can read more here: https://github.com/captbaritone/grats/blob/2f7323fb43a31ed1895b394bbdbc01fba583cc0c/CONTRIBUTING.md#automated-tests

**Comment by captbaritone** [comment]
@Rash-Hit Following up here. Are you still interested in working on this? No worries if not.

**Comment by Rash-Hit** [comment]
i am really sorry  @captbaritone  , is this something we need to do ?? 
![image](https://github.com/captbaritone/grats/assets/73944177/219e0d32-151a-49d5-85aa-98437b5e8625)

**Comment by captbaritone** [comment]
@Rash-Hit Yeah, that looks about right. We probably also need to check that it's `as const` (look at the `.identifier` of the as expression. You'll also need to make sure that in the as const case you look for the literal name string as the `.expression` of the as expression node.

Here's what it looks like in the correct case:
<img width="1605" alt="Screenshot 2024-03-23 at 12 22 04 PM" src="https://github.com/captbaritone/grats/assets/162735/818d2dd3-c0b8-4830-b3a9-03d987a14e04">

https://astexplorer.net/#/gist/615fac072e169328425c18cb9d88ba66/bea0aafa2f40091c2d62bf65dae3b3834d8bdf0a

**Comment by captbaritone** [comment]
Closed in https://github.com/captbaritone/grats/pull/137
