### ISSUE TITLE
Example: likes' count

### ISSUE THREAD

**Issue by artola** [captbaritone/grats#140]
The `count` field in `likes` does not reflect the value after a mutation:

```graphql
mutation M {
  createLike(input: {postId: "UG9zdDo1"}) {
    post {
      id
      likes {
        count
      }
    }
  }
}
```

```json
{
  "data": {
    "createLike": {
      "post": {
        "id": "UG9zdDo1",
        "likes": {
          "count": 0
        }
      }
    }
  }
}
```

What is clearly wrong as the `createLike` when happens (args are valid) must alter the number.

I do believe that here the global id must be mapped to the real id:

https://github.com/captbaritone/grats/blob/a6ebf81d8e96709fddd2c2c74eb8810132e07a9c/examples/production-app/models/Like.ts#L61

For example using the computed "id" value:

```ts
 await DB.createLike(ctx.vc, {...args.input, userId: ctx.vc.userId(), postId: id});
```

**Comment by captbaritone** [comment]
Thanks for the report. Should be fixed in https://github.com/captbaritone/grats/commit/5a491bbf7d2ffa5e5a92e86f03314657d322245f
