### ISSUE TITLE
VSCode plugin not working with TS 5.5.2

### ISSUE THREAD

**Issue by sikanhe** [captbaritone/grats#142]
Grats CLI is working but getting errors with the editor plugin

```
Unexpected Grats tag in detached docblock. Grats was unable to determine which TypeScript declaration this docblock is associated with. Moving the docblock to a position with is unambiguously "above" the relevant declaration may help. For more information see: https://grats.capt.dev/docs/getting-started/comment-syntaxGrats(1038)
```

<img width="715" alt="image" src="https://github.com/captbaritone/grats/assets/10578561/94cf7dfb-ada2-47ac-95ba-fcf46350f981">

**Comment by captbaritone** [comment]
Note to self: this is likely related to https://github.com/microsoft/TypeScript/pull/55739

**Comment by captbaritone** [comment]
Hmm, I'm unable to reproduce this. I've tried to create a repro here: https://github.com/captbaritone/grats-issue-142-repro

**Comment by captbaritone** [comment]
Update, I was able to trigger the issue in my repo by making this change: https://github.com/captbaritone/grats-issue-142-repro/commit/1f3c4363b711b4a5951fec9adbcf10a1ab8acf8f
