### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by kansson** [captbaritone/grats#148]
Hi, great project! Is it possible to use arrow functions for field definitions like this?
```ts
export const hello = (_: Query): string => 'Hello World!';
```

**Comment by captbaritone** [comment]
Yeah, should be possible. Happy to work on adding that. Quick question though, what's your motivation for preferring arrow functions? Just style?

**Comment by kansson** [comment]
> Yeah, should be possible. Happy to work on adding that. Quick question though, what's your motivation for preferring arrow functions? Just style?

Thanks, looking forward to it. Mainly for coding style and avoiding explicit returns in simple database queries.

**Comment by captbaritone** [comment]
Got it. That should be possible. I'll use this issue to track.

One common reason to want arrow functions is to apply wrappers, and that won't work (which is why I was asking).

**Comment by kansson** [comment]
Awesome thanks! 🚀
