### ISSUE TITLE
Improper Node interface

### ISSUE THREAD

**Issue by artola** [captbaritone/grats#153]
Is not wrong that in`Node` the `id` is not `ID!`?

https://github.com/captbaritone/grats/blob/ac1e6769ec0431c7e1c2e6aa082c924a21da18f4/examples/production-app/schema.graphql#L19

> Node Interface
The server must provide an interface called Node. That interface must include exactly one field, called id that returns a non-null ID.

See: https://graphql.org/learn/global-object-identification/#node-interface

**Comment by captbaritone** [comment]
Good catch. This should be using `@killsParentOnException`

https://grats.capt.dev/docs/resolvers/nullability/

**Comment by artola** [comment]
> https://grats.capt.dev/docs/resolvers/nullability/

@captbaritone You are right, and the problem is a typo (extra `s`) here: https://github.com/captbaritone/grats/blob/ac1e6769ec0431c7e1c2e6aa082c924a21da18f4/examples/production-app/graphql/Node.ts#L33

**Comment by artola** [comment]
@captbaritone, will you push a fix for the example, or do you want me to PR that?
