### ISSUE TITLE
Multiline comments / descriptions

### ISSUE THREAD

**Issue by willruggiano** [captbaritone/grats#155]
It would be nice if a line break (in TS comments) did not always manifest as a newline in the generated graphql schema. This is super nit picky obviously, but looks weird in e.g. graphiql.

For example, I would expect this to be a "single line" description:
```ts
/*
 * This is a really long description that takes up
 * multiple lines because maybe my editor or formatter
 * automatically split them up for me!
 * 
 * @gqlType
 */
type Foo = {
  ...
};
```

but the generated schema currently would be (note the newlines):
```ts
    description:
      "This is a really long description that takes up\nmultiple lines because maybe my editor or formatter\nautomatically split them up for me!",
```

vs a multi line description accomplished via an explicit empty line;
```ts
/*
 * This is a really long description that takes up
 * multiple lines because maybe my editor or formatter
 * automatically split up the lines on my behalf!
 *                                                     <-- explicit empty line
 * A new line!
 * 
 * @gqlType
 */
type Foo = {
  ...
};
```

**Comment by willruggiano** [comment]
I assume however that this is just a typescript / jsdoc limitation and there is in fact nothing that grats can do :/

**Comment by captbaritone** [comment]
The expectation in both GraphQL and TypeScript is that these descriptions are in Markdown. Line breaks in Markdown are not significant, so in theory we could collapse single line breaks to just spaces and still be ~correct. That said, I think that would require us to do some degree of pretty-printing somewhere. Also, multiple line breaks _are_ significant in markdown (paragraph breaks) so we can't get rid of them all together.

Note that the _main_ place these descriptions get surfaced are in the schema SDL. There the line breaks are preserved as line breaks, and I think it looks reasonable:

```graphql
"""
This is a really long description that takes up
multiple lines because maybe my editor or formatter
automatically split them up for me!
"""
type Foo {
  name: String
}
```

[Playground Link](https://grats.capt.dev/playground#N4IgJg9gxiBcIHoBUSAEABA5gRwDYBUBPABwFNUkEAdAOwBcTyBFAV1ICdDUBeVFmgNY0IAdxoBuWrWRoseAGIBLUrjAVqNUgA9iEdnVQAzflDqKINVAFtSACgD6sVKw6EAlE4CqAZw4AlUm8IXAA3DlRgWlRUdlI6FnZLTRFUH39A4LD2WzdJGgBfKRoZKNkcXCUVMFKMMFJiWKgAQzpSNQAFXFIm3z5egAMbftRFGm9WprAAOlKNbV19IxMzC1QQ5REOBycXTg9U33YAoNDwyMsYuISk0hS0o4zT7NzaQpppFBqAQT7w0dQIAlUAJFFABABaHreVDeQjjUhWACENTkBEYBw4s1oUFwUIxDxOWQiUVQMgw5UqqnUJJoTRsTnG7FGmB4qCoIC+uFBpHZeRJZNRlLUlBJmFicWZtm8TVwLDoLXMNAZdCZNEw+0ZzOJF2isXiiVQ-QAJMBpbL5SsCgAaVAmugAC0U3imtJs+X6eWibzeHyQNXwjuhTtQTUuMtwXFwFhZdW8UCZxEtqAdLWTTQEgT4xBqVhYuDMxC6qC5mmhACNSM0WL0rE1CBXrFw2oo6HoAewjHpa3RWuwak05RBu6Dw1xvIWW8n7Qis52OzZkZY0CjykQyFj6Oj5BAIKzztEBRTlFSRRdXaRlarMK9xCArSAoBZDIpMHBQDQ87iy10AEKEAAipCGAO+ZwCqbD3rECx0GupAAMrxooiawQAouw7B6N4YHsGw+T3ustxviAgJ0MQcoAPKJoqcAgAwZBxgmdB3iA3j2qIADi7AtN4-6KI0ZhhFhsDAbgvh4SAABqKF+HBACS5EAHJwAAjPkQA)

In general I think the generated typescript schema file is not _really_ intended to be read by humans. Maybe _inspected_ by humans if they wish, or a place you could set a breakpoint, but not something I expect folks to be looking at on a regular basis. So I'm not that concerned about how elegant that code looks as long as it's debuggable and easy to reason about.

Does that make senese?

**Comment by willruggiano** [comment]
Yeah totally agreed on the generated typescript schema. I am talking about the graphql schema.

```graphql
"""
This is a really long description that takes up
multiple lines because maybe my editor or formatter
automatically split them up for me!
"""
type Foo {
  name: String
}
```

looks weird in something like graphiql or ruru since they render the line breaks as is (same as if I'd written these descriptions by hand). Whereas what I'd like (caveat: nit pick) is this:

```graphql
"""
This is a really long description that takes up multiple lines because maybe my editor or formatter automatically split them up for me!
"""
type Foo {
  name: String
}
```

All a single line.

**Comment by willruggiano** [comment]
and to your point, the distinction is line breaks vs paragraph breaks. To my point, I don't see a way of writing my comments such that it obeys the laws of my editor / linter / formatter / whatever _and_ allows me to craft multi paragraph descriptions

**Comment by captbaritone** [comment]
Sounds like the tension is that your TypeScript editor linter enforces line breaks which you'd rather not have in your SDL description combined with graphiql/ruru rendering single line breaks, which it technically should not if its treating them as Markdown which, as you point out, should not treat single line breaks as significant.

Can you not relax the rules of your editor/linter? Or maybe look into getting graphiql/ruru to ignore insignificant whitespace?

I feel like the line breaks in TypeScript docblocks and in GraphQL description headers should be able to be close enough to allow Grats to simply copy the text over with the same line breaks. More practically, I don't think Grats can reflow markdown without including a Markdown parser, which I think is in tension with [my goal of keeping Grats' dependencies minimal](https://grats.capt.dev/docs/faq/design-principles/#a-few-dependencies-well-leveraged).

**Comment by willruggiano** [comment]
Yeah definitely, I think grats is doing exactly what it should be doing.

Well anyways, cheers! And thanks for the discussion!
