### ISSUE TITLE
Force optional args to accept null

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/grats#18]
If a field arg is typed in the DSL as optional, a request that passes an explicit null, is considered valid. This means `graphql-js` will pass through a user's explicit null. This, in turn, means that if Grats is going to generate an optional argument, the user's field resolver _must_ be capable of accepting `null`.

Today it's possible to define a function which is not expecting in its typescript types, but could get passed a null at runtime:

```typescript
/** @gqlType */
export default class Query {
  /** @gqlField */
  someField(args: {greeting: string | undefined}): string {
    if(args.greeting === undefined) {
      return "Hello!"
    }
    return args.greeting; // OOPS! Might return `null` here, which is not a `string`.
  }
}
```

```graphql
type Query {
  someField(greeting: String): String
}
```
[Playground](https://grats.capt.dev/playground#N4IgJg9gxiBcIHoBUSAEABA5gRwDYBUBPABwFNUkEAdAO1IA9iIAnAF1TFIDMBDAV1zsouHgGdRqAIp9SzQqmC1UqZGix4AYgEtSuMBWo1loiAFtS23WAAUPZplGwFmZqVKstNTE9GtmnzFQAH1Q+Gk4uT1IwAF8ASh8-AIUlZVQtLlt7UQA6FzcPL1QAXlLQ8O4osDiUozTlV1Y+ZiMqEAAJXVwIAEI21OUYgdRG5qM7BzzXdwCAblShmhiQABoQKAgaSMw4UBoBEQAjXFIAIUIAEW5+QTg-GTXXJjYiMgBlKH9iVlfSAFFmMwWKI7swZDE1gA3HQAd12IFEAAsIDCAOLMHisUQXLSuKAeSGkEGwXi4USkCEgABqfwASm8AJIAeQAcnAAIwxIA)

I think the best solution here is for Grats to error in this case and force you to add `| null` to the argument's type.

**Comment by mandx** [comment]
IMO it's the only type-safe solution, since Grats can't/won't alter how `graphql-js` handles this case?

**Comment by captbaritone** [comment]
In theory when we do applyServerDirectves (or in some similar place) we could wrap the resolver functions to match what the user-defined code expects, but I think that's probably not the right direction to head.

**Comment by captbaritone** [comment]
This has been fixed
