### ISSUE TITLE
Can't use `async` or `Promise` in the playground: it errors complaining about an older `lib` target

### ISSUE THREAD

**Issue by mandx** [captbaritone/grats#19]
As of 2023-10-30, when entering this code in the playground:
```ts
/** @gqlType */
class Query {
  /**
   * @gqlField
   */
  async test(): Promise<string> {
    return '';
  }
}
```
We get an error about `Promise` not being defined:
```
# ERROR MESSAGE
# =============

# index.ts:6:17 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
# 
# 6   async test(): Promise<string> {
#                   ~~~~~~~~~~~~~~~
# 
```
I thought this was going to be an easy thing to fix, except, it looks like the playground's TS config [already targets a recent environment](https://github.com/captbaritone/grats/blob/3e9d666002a5eef96cc2d5364dddb20d5af6535c/website/src/components/PlaygroundFeatures/editors/InputView.tsx#L50) (ES2021)?

```ts
    createDefaultMapFromCDN(
      { target: ts.ScriptTarget.ES2021, lib: ["es2021"] },
      ts.version,
      shouldCache,
      ts,
      lzstring,
    )
```

However, I also found this [commented line](https://github.com/captbaritone/grats/blob/3e9d666002a5eef96cc2d5364dddb20d5af6535c/website/src/components/PlaygroundFeatures/linter.ts#L37):
```
  const compilerOpts = {
    allowJs: true,
    baseUrl: "./",
    paths: { grats: [GRATS_PATH] },
    // lib: ["es2021"],
  };
  const host = createVirtualCompilerHost(system, compilerOpts, ts);
```
I'm curious what is the Chesterton's Fence reason for having `lib: ["es2021"]` in one component but not in the other?

**Comment by captbaritone** [comment]
Thanks for documenting this gap. I had a private note about it [here](https://github.com/captbaritone/grats/blob/main/TODO.md?plain=1#L17), but I'm happy to have it tracked as a formal issue.

I forget what it was that lead me to comment out `lib: ["es2021"],` but I have a vague recollection that there was some bug with the in-browser version of the TypeScript compiler where the CDN that hosts the type definitions for each version of the compiler wasn't working for that specific version? I forget exactly. If someone wants to try building the docs/playground and uncomment that line and report back, that would be a good start. Otherwise, I'll get to this eventually.

**Comment by captbaritone** [comment]
Sorry if I'm missing something. What's the "Chesterton's Fence" reference?

**Comment by mandx** [comment]
> Sorry if I'm missing something. What's the "Chesterton's Fence" reference?

https://fs.blog/chestertons-fence/

I simply thought "maybe there's an important reason that explains why is commented out", so I just asked why, rather than just change the code and push a PR without any context :smile:

**Comment by captbaritone** [comment]
I tried removing the commented line, and here's the error it creates:

```
# ERROR MESSAGE
# =============

# Grats playground bug encountered. Please report this error:
# 
#  TypeError: Cannot read properties of undefined (reading 'length')
#     at iterateCommentRanges (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:9419:37)
#     at reduceEachLeadingCommentRange (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:9523:12)
#     at getLeadingCommentRanges (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:9553:12)
#     at getJSDocCommentRanges (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:14093:429)
#     at addJSDocComment (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:28766:36)
#     at parseSourceFileWorker (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:28740:34)
#     at Object.parseSourceFile (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:28571:26)
#     at Object.createSourceFile (webpack-internal:///../node_modules/.pnpm/typescript@5.0.2/node_modules/typescript/lib/typescript.js:27759:23)
#     at Object.getSourceFile (webpack-internal:///../node_modules/.pnpm/@typescript+vfs@1.4.0/node_modules/@typescript/vfs/dist/vfs.esm.js:492:53)
#     at findSourceFileWorker (webpack-internal:///../node_modules/typescript/lib/typescript.js:121027:29)
```

Specifically it errors when it's trying to call `getSourceFile` for `"/es2021.ts"`. I'll dig more.

**Comment by captbaritone** [comment]
Ah, I think this PR is relevant: https://github.com/microsoft/TypeScript-Website/pull/2802/files

**Comment by captbaritone** [comment]
[Playground example with promise](https://grats.capt.dev/playground#N4IgJg9gxiBcIHoBUSAEABA5gRwDYBUBPABwFNUkEAdAO1IA9iIAnAF1TFIDMBDAV1zsouHgGdRqAIp9SzQqmC1UqZGix4AYgEtSuMBWo1lYwjSipMzUqVZaamABQBKWKgAKzCAFsto0gB5RVmY7TAA+BSVlVCtWPmYjKhAACV1cCCSAbiiAX1o8mhAAGhAoCBouLUw4UBoBEQAjXFIAIUIAEW5+QThgmRKrJjYiMgBlKBDiVhHSAFFmT2ZRXuYZHJKANx0AdxqQUQALCG2AcWYeVlF2rSsoWw3SZdheXD91kAA1WYAlUYBJADyADk4ABGHJAA)

<img width="1158" alt="Screenshot 2023-10-30 at 11 14 41 PM" src="https://github.com/captbaritone/grats/assets/162735/552db7e5-87fb-47a3-9bc5-a8a2901c9191">

**Comment by captbaritone** [comment]
This broke upon deploy, so I'm reverting it. Strange because it worked locally and now does not. Need to see what happened. I suspect I had gotten my local setup into a state where the installed dependencies (typescript maybe?) were on a different version that what is specified in package.json or my lock file.

https://github.com/captbaritone/grats/pull/27
