### ISSUE TITLE
Support defining GraphQL types as TypeScript interfaces

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/grats#2]
We currently support extracting GraphQL type definitions from TypeScript class definitions and GraphQL interface definitions from TypeScript interface definitions. But it is reasonable that someone might want to expose an interface in their TypeScript code as a GraphQL type.

```ts
/** GQLType */
interface MyType {
  /** GQLField */
  myField: string
}
```

Should generate:

```graphql
type MyType {
  myField: String
}
```

## Pointers

- [ ] Add a new case in [`Extractor.extractType`](https://github.com/captbaritone/grats/blob/d80309c9eeb59c66c411a25b4746acdc353b4e95/src/Extractor.ts#L116) to handle interface definitions
- [ ] Copy the implementation of [`Extractor.typeClassDeclaration`](https://github.com/captbaritone/grats/blob/d80309c9eeb59c66c411a25b4746acdc353b4e95/src/Extractor.ts#L367) into a new method named `typeInterfaceDeclaration`, and make the necessary changes.
- [ ] Create a new fixture directory that's a copy of [`fixtures/type_definition`](https://github.com/captbaritone/grats/tree/d80309c9eeb59c66c411a25b4746acdc353b4e95/src/tests/fixtures/type_definitions) and its contents and call it `fixtures/type_definition_from_interface` or similar. Update all the tests to use interfaces.
- [ ] Add documentation to the readme file indicating that interfaces can be used, and give an example.

See [CONTRIBUTING.md](https://github.com/captbaritone/grats/blob/main/CONTRIBUTING.md) for project level guidance.

**Comment by leoasis** [comment]
initial thought here, in this way of defining types, would we want to assume that all fields in an interface would be exposed implicitly? Instead of having to explicitly specify each with the GQLField JSDoc, I could see a point for making types and interfaces being the fields we want to expose as a type. 

This is just to trigger the discussion, not necessarily to make the decision as part of this ticket.

**Comment by captbaritone** [comment]
I think it makes sense for fields to always be opt-in. My view is that most systems probably already have classes/types that model their various graphql types. Rather than asking them to define new types just to expose them in GraphQL, they should be able to annotate their existing types, opting in only the fields that make sense to be public, and renaming types/fields to public facing names as they go.
