### ISSUE TITLE
Class which extends one interface and implements another only gets the implemented interface in schema definition

### ISSUE THREAD

**Issue by calirvine** [captbaritone/grats#83]
Given the following typescript definitions:
```ts
/**
 * @gqlInterface Node
 */
export interface Node {
  /** @gqlField */
  id: string;
}

/** @gqlInterface Something */
interface SomethingElse {
  /** @gqlField */
  hello: string;
}

/** @gqlType */
export class User extends Node implements SomethingElse {
  __typename: "User";
  /** @gqlField */
  id: string;
  /** @gqlField */
  hello: string;
  /** @gqlField */
  username: string;
  /** @gqlField */
  email: string;
}
```

We get the generated type
```graphql
type User implements SomethingElse {
  email: String
  hello: String
  id: String
  username: String
}
```

But if we switch `User` to implement both `Node` and `SomethingElse` rather than extending one, we get both correctly added to the generated schema

```graphql
type User implements Node & SomethingElse {
  email: String
  hello: String
  id: String
  username: String
}
```

Given that both `extends` and `implements` are supported for interfaces, I would expect both to work when applied to the same class.

**Comment by captbaritone** [comment]
Interesting and thanks for reporting. I wasn't aware of this TypeScript behavior, and I don't see it mentioned in the [handbook](https://www.typescriptlang.org/docs/handbook/2/classes.html#class-heritage). Do you happen to know where its behavior is specified?

[Trying it in the TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgHIHsAmKDeAoZQ5YTALmQGcwpQBzPAXzzwQBs4KLkAxddZCAA9IITFwzZk+QgHoZadJHIZimZDGARWmAISNmeGAFcQCMMHQhkAIzhQAFCCwRlzgJTkqNELSkEiUBBgRlBWTtgAdCQA3MhyyACSyGAAFqAA1slpXMBcJhRwMBAA-PrMtg4gEADuPHz2bm7RQA), it looks like this pattern is not typesafe since it does not ensure the class actually implements the interface?

Is this a pattern you are actively hoping to use, or just a behavior you found confusing in Grats? If it's the former, I'd love to hear more about what value this pattern provides.

Thanks again for the report.

**Comment by calirvine** [comment]
> Interesting and thanks for reporting. I wasn't aware of this TypeScript behavior, and I don't see it mentioned in the [handbook](https://www.typescriptlang.org/docs/handbook/2/classes.html#class-heritage). Do you happen to know where its behavior is specified?

I think the behaviour probably exists due to the weird relationship between classes and interfaces in typescript, they seem to be treated similarly due to their ability to merge declarations. (i.e [this weird behaviour, which is equally unsafe](https://www.typescriptlang.org/play?#code/FDCWDsBcFMCcDMCGBjaACAYgey2g3sGkWqACYBcaAzpLBAObAC+IyANolVZjvoWgHoBaAHJYYlMSVJp4oaG1IBCZqw5c0AIUSw00AB4xwpbtlx4WwZFnA00kABYM0AXjThoAdx5YAFAEoAbhBHBgA6MlYbO1DwegAmV3cvLR0A4OBYhIjSIA))

I agree that it's not type safe, you shouldn't extend from an interface, just from another class. It's just something I stumbled upon when playing around, my first class implementing an interface I used extend because I misread the documentation ([this section](https://grats.capt.dev/docs/docblock-tags/interfaces#interfaces-implementing-interfaces)) and it compiled fine, then I wondered how you would apply more than one interface when you can't extend from more than one class and realized I should be using implements. I then was curious what would happen if I both extended and implements. Admittedly, this is not normal user behaviour 😅 but I think the grats compiler should know what to do in the case that a graphql interface is used to extend a type. 

I think the correct solution would be to throw an error when a concrete type tries to extend from an interface, and only allow `extend` for interfaces implementing each other. I'm not sure how realistic this is though, as the TypeScript compiler seems happy to treat classes and interfaces as mostly interchangeable.

**Comment by captbaritone** [comment]
Posted about this on Twitter and it's actually because `Node` happens to be a globally defined class! https://twitter.com/captbaritone/status/1736811340550091224

Maybe our docs should specifically call out this namespace collision with a note since `Node` is a common name for GraphQL interfaces.

**Comment by captbaritone** [comment]
Maybe we should actually go a step further and make it a (helpful!) error to define an interface where the TS name is `Node`.

**Comment by captbaritone** [comment]
So, I knew about merged interfaces, but didn't know you could merge interfaces and classes. https://github.com/captbaritone/grats/pull/84 extends our existing interface merging validation to also catch this example.

**Comment by sikanhe** [comment]
Yea I named my interface `GqlNode`
